version: '3'

tasks:
  init:
    desc: Initialize the project
    cmds:
      - docker compose run --rm web rails new --api . --database=postgresql

  bundle_install:
    desc: Install the gems
    cmds:
      - docker compose run --rm web bundle install

  db_create:
    desc: Create the database
    cmds:
      - docker compose run --rm web rails db:create

  db_migrate:
    desc: Run the database migrations
    cmds:
      - docker compose run --rm web rails db:migrate

  db_drop:
    desc: Drop the database
    cmds:
      - docker compose run --rm web rails db:drop

  db_reset:
    desc: Reset the database
    cmds:
      - docker compose ren --rm web rails db:environment:set RAILS_ENV=development
      - docker compose run --rm web rails db:reset

  db_rollback:
    desc: Rollback the database
    cmds:
      - docker compose run --rm web rails db:rollback

  remove:
    desc: Remove the project
    cmds:
      - docker compose down --volumes

  test_db_create:
    desc: Create the test database
    cmds:
      - docker compose run --rm web rails db:create RAILS_ENV=test
      - docker compose run --rm web rails db:migrate RAILS_ENV=test

  test_all:
    desc: Run all tests
    cmds:
      - docker compose run --rm web rspec

  test_posts_spec:
    desc: Run the posts spec
    cmds:
      - docker compose run --rm web rspec spec/requests/api/v1/posts_spec.rb

  routes:
    desc: List all defined routes
    cmds:
      - docker compose run --rm web rails routes

  console:
    desc: Start a Rails console
    cmds:
      - docker compose run --rm web rails console

  generate_schema:
    desc: Generate database schema
    cmds:
      - docker compose run --rm web rails db:schema:dump
